### ISSUE TITLE
Generating blog post links on home page

### ISSUE THREAD

**Issue by paniash** [tlienart/FranklinTemplates.jl#113]
Hi!

Is there a way to generate blog posts on the main page? Something like [this](https://ashishpanigrahi.now.sh)

Apologies but I'm not very well-versed in HTML so I'd appreciate if you could help me.

Thanks!

**Comment by tlienart** [comment]
Hello, could you have a look at https://github.com/tlienart/Franklin.jl/issues/742 and the pointers I mention in there and see if it solves your question? 

Also look at the Franklin docs - syntax - utils.

Also if you have issues, consider joining the Julia slack channel franklin which is a better spot for asking usage question :)
