### ISSUE TITLE
Remove Hyde written at the beginning

### ISSUE THREAD

**Issue by aburousan** [tlienart/FranklinTemplates.jl#142]
How to remove the word Hyde written in the home page?
![IMG_20220222_123719](https://user-images.githubusercontent.com/60939745/155148561-031b765a-f410-4097-a810-ae29967c9430.jpg)

**Comment by tlienart** [comment]
Hello @aburousan, have a look at `_layout/sidebar.html` in your folder, you will be able to modify the text & the menu items

hth

PS: can I kindly suggest that you use [discourse](https://discourse.julialang.org) to ask usage questions so others can benefit from the answer? you might also like to join the `#Franklin` channel on the Julia slack.
