### ISSUE TITLE
just-the-docs template, bug with long titles

### ISSUE THREAD

**Issue by parfenyev** [tlienart/FranklinTemplates.jl#148]
Hello everyone!

I have found that very long titles do not wrap to a new line if they exceed the width of the page (please, see screenshort). How can this be fixed? Some other templates don't have this problem.

Thank you in advance!

![screenshort](https://user-images.githubusercontent.com/61187417/164311384-a0659b5b-3147-4e42-a544-a1abb605b4f7.png)

**Comment by tlienart** [comment]
in `_layout/style.html`, add

```
<style>
  .franklin-content h1 a.header-anchor {
    word-wrap: break-word;
    white-space: normal;
  }
</style>
```

<img width="827" alt="Screenshot 2022-04-21 at 08 55 11" src="https://user-images.githubusercontent.com/10897531/164392538-0016ee60-80eb-4d74-83de-d818d97b9aab.png">
