### ISSUE TITLE
just-the-docs template, long item in list

### ISSUE THREAD

**Issue by parfenyev** [tlienart/FranklinTemplates.jl#149]
I have also found that very long items in lists do not wrap to a new line if they contain hyperlinks (e.g., in table of contents). How can this be fixed? Thank you!

![screenshort](https://user-images.githubusercontent.com/61187417/164425946-09786ebf-15cc-4e3c-ae2a-336fadc9f1e8.jpg)

**Comment by tlienart** [comment]
the same CSS can be used as in #148 for `.franklin-toc li`

**Comment by tlienart** [comment]
Checking in the web developer tool you could have seen that it's just the `a` that was missing:

```
.franklin-content a.header-anchor,
.franklin-toc li a
 {
  word-wrap: break-word;
  white-space: normal;
}
```

**Comment by parfenyev** [comment]
Thanks, now everything works. Sorry for the simple questions, I'm not familiar with JavaScript.

**Comment by tlienart** [comment]
it's all CSS, not javascript. Glad things work!
