### ISSUE TITLE
CC BY-SA 4.0 License

### ISSUE THREAD

**Issue by clarkevans** [tlienart/FranklinTemplates.jl#153]
Is it your intent that everyone's content that builds upon one of these templates be licensed under CC BY-SA?  This seems at odds with the project's MIT license. If not, could this license declaration be removed?

**Comment by tlienart** [comment]
There's two elements here: a licensing of the code providing the templates (MIT) and the suggestion to license blog post content as cc by sa (which might help prevent people just copy pasting your content without attribution though of course that might be a pipe dream). MIT license is not very well suited for blog posts afaik.

In any case, all this can be removed by the user easily if they want to do something else, the code indicating the cc by sa is actually... MIT licensed 

Also cc'ing @rikhuijzer who I think is the one who introduced this default.

**Comment by rikhuijzer** [comment]
> Is it your intent that everyone's content that builds upon one of these templates be licensed under CC BY-SA? This seems at odds with the project's MIT license. If not, could this license declaration be removed?

Yes. I agree with Thibaut. You need two licenses, one for the code and one for the text because CC is not good a good license for code and MIT is not a good license for text. See, for example, https://discourse.julialang.org/t/changing-the-terms-of-service-user-content-license/34979 for more information

**Comment by rikhuijzer** [comment]
We could be more explicit about having the code licensed under MIT though? What do you both think?

**Comment by clarkevans** [comment]
I think we're good.  I just wanted to be assured of the licensing intent.  Let me close this item.
