### ISSUE TITLE
Made mistakes themes

### ISSUE THREAD

**Issue by tlienart** [tlienart/FranklinTemplates.jl#18]
* [x] minimal mistakes https://mmistakes.github.io/minimal-mistakes/ 
  * [x] main layout
  * [x] check links etc
  * [x] add to readme here and in judoc
* [ ] so simple https://mmistakes.github.io/so-simple-theme/
* [ ] basically basic https://mmistakes.github.io/jekyll-theme-basically-basic/

**Comment by tlienart** [comment]
ongoing on branch https://github.com/tlienart/JuDocTemplates.jl/tree/minimalmistakes

**Comment by aburousan** [comment]
Just want to ask one thing "minimal-mistakes" has a dark theme. Can we use that in Franklin? If yes, can you tell how?
