### ISSUE TITLE
Tufte: Font URLs do not get rewritten if `prepath` is set

### ISSUE THREAD

**Issue by shashi** [tlienart/FranklinTemplates.jl#53]
I guess it's because they're in the CSS file.

Pretty cool font!

**Comment by tlienart** [comment]
Good catch, thanks!

**Comment by tlienart** [comment]
Ok this is fixed, in order to fix it locally, open `_css/tufte.css` and find replace `"/assets` with `"../assets`

**Comment by shashi** [comment]
Clever fix! It worked for me, thank you!
