### ISSUE TITLE
Add GR.jl example in sandbox extended

### ISSUE THREAD

**Issue by terasakisatoshi** [tlienart/FranklinTemplates.jl#60]
- This example is taken from https://mybinder.org/v2/gh/jheinen/GR.jl/master . Let's add to sandbox extended :D
- The result should be like : https://terasakisatoshi.github.io/MathSeminar.jl/gallery/gr/

```julia
@def title = "GR.jl"

using GR
using LaTeXStrings
GR.inline("mov")
x = collect(0:0.01:2*pi)
for i = 1:100
    GR.plot(x, sin.(x .+ i / 10.0), size=(400,300))
end

s = GR.show()
# render HTML # hide
println("~~~") # hide
println(s.s) # hide 
println("~~~") #hide
\textoutput{gr}
```

**Comment by tlienart** [comment]
By the way @terasakisatoshi you should also open a PR on Franklin’s readme to advertise your site :-)
